name: Node Test/Lint CI

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run your tests
    env:
      LAYOUT_ID: ${{ vars.LAYOUT_ID }}
      LAYOUT_FOLDER: ${{ vars.LAYOUT_FOLDER }}
      CI: true
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
